"""PDF CV Generator — ATS-optimized CVs via HTML template + Playwright.

Creates keyword-injected CVs tailored to specific job descriptions.
Uses a clean, modern HTML template rendered to A4 PDF via Playwright.
"""

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger("job_hunting.ai.pdf")

ASSETS_DIR = Path(__file__).resolve().parent.parent / "templates"

CV_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  @page { size: A4; margin: 15mm 18mm 15mm 18mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 10.5pt;
    line-height: 1.55;
    color: #1a1a2e;
  }
  .header { text-align: center; margin-bottom: 18px; padding-bottom: 14px; border-bottom: 2.5px solid #2563eb; }
  .name { font-size: 24pt; font-weight: 700; letter-spacing: 0.5px; color: #1e3a5f; margin-bottom: 4px; }
  .contact { font-size: 9.5pt; color: #475569; }
  .contact a { color: #2563eb; text-decoration: none; }
  .section { margin-bottom: 14px; }
  .section-title { font-size: 11pt; font-weight: 700; color: #2563eb; text-transform: uppercase; letter-spacing: 1.2px; margin-bottom: 6px; padding-bottom: 3px; border-bottom: 1px solid #e2e8f0; }
  .summary-text { font-size: 10pt; color: #334155; margin-bottom: 8px; line-height: 1.6; }
  .job { margin-bottom: 10px; }
  .job-header { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 2px; }
  .job-title { font-weight: 700; font-size: 10.5pt; color: #1e293b; }
  .job-company { font-weight: 600; color: #475569; }
  .job-dates { font-size: 9pt; color: #94a3b8; white-space: nowrap; }
  .job-bullets { list-style: none; padding-left: 0; }
  .job-bullets li { position: relative; padding-left: 14px; margin-bottom: 3px; font-size: 10pt; color: #334155; }
  .job-bullets li::before { content: "▸"; position: absolute; left: 0; color: #2563eb; font-size: 8pt; }
  .skills-grid { display: flex; flex-wrap: wrap; gap: 6px; }
  .skill-tag { background: #eff6ff; color: #1e40af; padding: 3px 10px; border-radius: 12px; font-size: 9pt; font-weight: 500; }
  .skill-tag-match { background: #dcfce7; color: #166534; }
  .edu-item { margin-bottom: 4px; }
  .edu-degree { font-weight: 600; }
  .edu-school { color: #475569; }
  .edu-year { font-size: 9pt; color: #94a3b8; }
  .footer { margin-top: 20px; padding-top: 8px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 8pt; color: #94a3b8; }
</style>
</head>
<body>
<div class="header">
  <div class="name">$full_name</div>
  <div class="contact">$email | $phone | $location $linkedin</div>
</div>

<div class="section">
  <div class="section-title">Professional Summary</div>
  <div class="summary-text">$summary</div>
</div>

<div class="section">
  <div class="section-title">Skills</div>
  <div class="skills-grid">$skills_html</div>
</div>

<div class="section">
  <div class="section-title">Experience</div>
  $experience_html
</div>

<div class="section">
  <div class="section-title">Education</div>
  $education_html
</div>

$projects_html

$certifications_html

<div class="footer">Generated by Job Hunting AI | ATS-Optimized CV</div>
</body>
</html>"""


class CVGenerator:
    def generate_html(
        self,
        full_name: str,
        email: str,
        phone: str,
        location: str,
        summary: str,
        skills: list[str],
        experience: list[dict[str, Any]],
        education: list[dict[str, Any]],
        *,
        linkedin: str = "",
        projects: list[str] | None = None,
        certifications: list[str] | None = None,
        keyword_skills: list[str] | None = None,
    ) -> str:
        linkedin_str = f"| {linkedin}" if linkedin else ""

        keyword_set = {k.lower() for k in (keyword_skills or [])}

        skills_html = ""
        for skill in skills[:20]:
            cls = "skill-tag-match" if skill.lower() in keyword_set else ""
            skills_html += f'<span class="skill-tag {cls}">{skill}</span>\n'

        exp_html = ""
        for job in experience:
            title = job.get("title", "")
            company = job.get("company", "")
            dates = f"{job.get('start_date', '')} — {job.get('end_date', '')}"
            highlights = job.get("highlights", [])
            if isinstance(highlights, str):
                highlights = [highlights]
            bullets = "".join(f"<li>{h}</li>" for h in highlights[:5])
            exp_html += f"""<div class="job">
  <div class="job-header">
    <span class="job-title">{title}</span>
    <span class="job-dates">{dates}</span>
  </div>
  <div class="job-company">{company}</div>
  <ul class="job-bullets">{bullets}</ul>
</div>
"""

        edu_html = ""
        for edu in education:
            degree = edu.get("degree", "")
            field = edu.get("field", "")
            school = edu.get("school", "")
            year = edu.get("year", "")
            edu_html += f"""<div class="edu-item">
  <span class="edu-degree">{degree}{" in " + field if field else ""}</span>
  <span class="edu-school">{" — " + school if school else ""}</span>
  <span class="edu-year">{" (" + year + ")" if year else ""}</span>
</div>
"""

        projects_html = ""
        if projects:
            projects_html = '<div class="section"><div class="section-title">Projects</div>'
            for p in projects[:5]:
                projects_html += f'<div class="job-bullets"><li>{p}</li></div>'
            projects_html += "</div>"

        certs_html = ""
        if certifications:
            certs_html = '<div class="section"><div class="section-title">Certifications</div>'
            certs_html += '<div class="skills-grid">'
            for c in certifications[:8]:
                certs_html += f'<span class="skill-tag">{c}</span>'
            certs_html += "</div></div>"

        return (
            CV_TEMPLATE.replace("$full_name", full_name)
            .replace("$email", email)
            .replace("$phone", phone)
            .replace("$location", location)
            .replace("$linkedin", linkedin_str)
            .replace("$summary", summary)
            .replace("$skills_html", skills_html)
            .replace("$experience_html", exp_html)
            .replace("$education_html", edu_html)
            .replace("$projects_html", projects_html)
            .replace("$certifications_html", certs_html)
        )

    async def generate_pdf(
        self,
        html: str,
        output_path: str = "output/cv.pdf",
    ) -> str:
        try:
            from playwright.async_api import async_playwright

            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=True)
                page = await browser.new_page()
                await page.set_content(html, wait_until="networkidle")
                await page.pdf(
                    path=output_path,
                    format="A4",
                    margin={"top": "15mm", "bottom": "15mm", "left": "18mm", "right": "18mm"},
                    print_background=True,
                )
                await browser.close()
            logger.info("PDF generated: %s", output_path)
            return output_path
        except ImportError:
            logger.warning("Playwright not available — saving HTML only")
            html_path = output_path.replace(".pdf", ".html")
            Path(html_path).write_text(html, encoding="utf-8")
            return html_path
